name: Print Python File

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development

jobs:
  print-python-file:
    runs-on: ubuntu-latest

    steps:
      - name: Print selected environment
        run: |
          echo "Environment selected: ${{ github.event.inputs.environment }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print contents of test.py
        run: |
          echo "--- test.py content ---"
          cat SpringbootProj/test.py
