name: Read Input Demo

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'John Doe'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print input variables
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
          echo "Environment: ${{ github.event.inputs.environment }}"
