name: Run Shell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make advanced script executable
        run: chmod +x ./SpringbootProj/advanced-hello.sh

      - name: Run advanced hello script
        run: ./SpringbootProj/advanced-hello.sh --name "GitHub Runner"
