name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development

jobs:
  print-choice:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected environment
        run: |
          echo "Environment selected: ${{ github.event.inputs.environment }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven


      - name: Build and test
        run: mvn -B clean package
          - uses: actions/upload-artifact@v3
             with:
                  name: my-app-artifact
                  ath: target/*.jar

          
