name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development

jobs:
  print-choice:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected environment
        run: |
          echo "Environment selected: ${{ github.event.inputs.environment }}"
